# formletter.pl --
#
# UI generated by GUI Builder v1.0on 2002-12-01 14:45:53 from:
#	C:/Evan/source/Perl/formletter.ui
# This file is auto-generated.  It may be modified with the
# following restrictions:
#	1. Only code in 'sub' functions is round-tripped.
#

# Declare the package for this dialog
package formletter;

# FindBin locates the real dir location of this script
use FindBin qw($RealBin);
use lib $RealBin;
eval 'require "formletter_ui.pl";';
die $@ if $@;

# text_6_xscrollcommand --
#
# Here we create a command that handles the 
# -xscrollcommand option for the widget text_6
#
# ARGS:
#    
#
sub text_6_xscrollcommand {};
# text_6_yscrollcommand --
#
# Here we create a command that handles the 
# -yscrollcommand option for the widget text_6
#
# ARGS:
#    
#
sub text_6_yscrollcommand {};
# radiobutton_8_command --
#
# Here we create a command that handles the 
# -command option for the widget radiobutton_8
#
# ARGS:
#    
#
sub radiobutton_8_command {};
# radiobutton_9_command --
#
# Here we create a command that handles the 
# -command option for the widget radiobutton_9
#
# ARGS:
#    
#
sub radiobutton_9_command {};
# radiobutton_10_command --
#
# Here we create a command that handles the 
# -command option for the widget radiobutton_10
#
# ARGS:
#    
#
sub radiobutton_10_command {};
# radiobutton_11_command --
#
# Here we create a command that handles the 
# -command option for the widget radiobutton_11
#
# ARGS:
#    
#
sub radiobutton_11_command {};
# checkbutton_2_command --
#
# Here we create a command that handles the 
# -command option for the widget checkbutton_2
#
# ARGS:
#    
#
sub checkbutton_2_command {};
# text_1_xscrollcommand --
#
# Here we create a command that handles the 
# -xscrollcommand option for the widget text_1
#
# ARGS:
#    
#
sub text_1_xscrollcommand {};
# text_1_yscrollcommand --
#
# Here we create a command that handles the 
# -yscrollcommand option for the widget text_1
#
# ARGS:
#    
#
sub text_1_yscrollcommand {};
# checkbutton_3_command --
#
# Here we create a command that handles the 
# -command option for the widget checkbutton_3
#
# ARGS:
#    
#
sub checkbutton_3_command {};
# text_2_xscrollcommand --
#
# Here we create a command that handles the 
# -xscrollcommand option for the widget text_2
#
# ARGS:
#    
#
sub text_2_xscrollcommand {};
# text_2_yscrollcommand --
#
# Here we create a command that handles the 
# -yscrollcommand option for the widget text_2
#
# ARGS:
#    
#
sub text_2_yscrollcommand {};
# checkbutton_4_command --
#
# Here we create a command that handles the 
# -command option for the widget checkbutton_4
#
# ARGS:
#    
#
sub checkbutton_4_command {};
# text_4_xscrollcommand --
#
# Here we create a command that handles the 
# -xscrollcommand option for the widget text_4
#
# ARGS:
#    
#
sub text_4_xscrollcommand {};
# text_4_yscrollcommand --
#
# Here we create a command that handles the 
# -yscrollcommand option for the widget text_4
#
# ARGS:
#    
#
sub text_4_yscrollcommand {};
# checkbutton_5_command --
#
# Here we create a command that handles the 
# -command option for the widget checkbutton_5
#
# ARGS:
#    
#
sub checkbutton_5_command {};
# text_5_xscrollcommand --
#
# Here we create a command that handles the 
# -xscrollcommand option for the widget text_5
#
# ARGS:
#    
#
sub text_5_xscrollcommand {};
# text_5_yscrollcommand --
#
# Here we create a command that handles the 
# -yscrollcommand option for the widget text_5
#
# ARGS:
#    
#
sub text_5_yscrollcommand {};
# checkbutton_6_command --
#
# Here we create a command that handles the 
# -command option for the widget checkbutton_6
#
# ARGS:
#    
#
sub checkbutton_6_command {};
# text_7_xscrollcommand --
#
# Here we create a command that handles the 
# -xscrollcommand option for the widget text_7
#
# ARGS:
#    
#
sub text_7_xscrollcommand {};
# text_7_yscrollcommand --
#
# Here we create a command that handles the 
# -yscrollcommand option for the widget text_7
#
# ARGS:
#    
#
sub text_7_yscrollcommand {};
# button_1_command --
#
# Here we create a command that handles the 
# -command option for the widget button_1
#
# ARGS:
#    
#
sub button_1_command {};
# button_2_command --
#
# Here we create a command that handles the 
# -command option for the widget button_2
#
# ARGS:
#    
#
sub button_2_command {};


# Standalone Code Initialization

if (defined &formletter::userinit) {
formletter::userinit();
}

our($top) = MainWindow->new();
$top->title("formletter");
formletter::ui($top);

if (defined &formletter::run) {
formletter::run();
}

Tk::MainLoop();

1;
