#=============================================================================================
# Method    : insert_auction
# Added     : 31/07/05
# Input     : Hash containg filed/value pairs
# Returns   : Key of new record
#
# Add an Auction Record to the databaSe 
#=============================================================================================

sub insert_auction {

    my $input = { @_ };
    my $record;
    my $lastkey;
    my $newkey;

    # Set default values for new record
    # Key value AuctionKey is defined as Autonumber and will be generated by the database
    
    $record->{ AuctionKey           }   = 0             ;               
    $record->{ Title                }   = ""            ;               
    $record->{ Subtitle             }   = ""            ;               
    $record->{ Description          }   = ""            ;               
    $record->{ ProductType          }   = ""            ;               
    $record->{ ProductCode          }   = ""            ;               
    $record->{ ProductCode2         }   = ""            ;               
    $record->{ SupplierRef          }   = ""            ;               
    $record->{ LoadSequence         }   = 0             ;                
    $record->{ Held                 }   = 0             ;                
    $record->{ AuctionCycle         }   = ""            ;               
    $record->{ AuctionStatus        }   = ""            ;               
    $record->{ RelistStatus         }   = 0             ;               
    $record->{ AuctionSold          }   = 0             ;               
    $record->{ StockOnHand          }   = 0             ;                
    $record->{ RelistCount          }   = 0             ;                
    $record->{ NotifyWatchers       }   = 0             ;                
    $record->{ UseTemplate          }   = 0             ;                
    $record->{ TemplateKey          }   = 0             ;                
    $record->{ AuctionRef           }   = ""            ;               
    $record->{ SellerRef            }   = ""            ;               
    $record->{ DateLoaded           }   = "01/01/2000"  ;     
    $record->{ CloseDate            }   = "01/01/2000"  ;     
    $record->{ CloseTime            }   = "00:00:01"    ;       
    $record->{ Category             }   = ""            ;               
    $record->{ MovieRating          }   = 0             ;                
    $record->{ MovieConfirm         }   = 0             ;                
    $record->{ AttributeCategory    }   = 0             ;               
    $record->{ AttributeName        }   = ""            ;               
    $record->{ AttributeValue       }   = ""            ;               
    $record->{ TMATT038             }   = ""            ;               
    $record->{ TMATT104             }   = ""            ;               
    $record->{ TMATT104_2           }   = ""            ;               
    $record->{ TMATT106             }   = ""            ;               
    $record->{ TMATT106_2           }   = ""            ;               
    $record->{ TMATT108             }   = ""            ;               
    $record->{ TMATT108_2           }   = ""            ;               
    $record->{ TMATT111             }   = ""            ;               
    $record->{ TMATT112             }   = ""            ;               
    $record->{ TMATT115             }   = ""            ;               
    $record->{ TMATT117             }   = ""            ;               
    $record->{ TMATT118             }   = ""            ;               
    $record->{ TMATT163             }   = ""            ;               
    $record->{ TMATT164             }   = ""            ;               
    $record->{ IsNew                }   = 0             ;                
    $record->{ TMBuyerEmail         }   = 0             ;                
    $record->{ StartPrice           }   = 0             ;                
    $record->{ ReservePrice         }   = 0             ;                
    $record->{ BuyNowPrice          }   = 0             ;                
    $record->{ EndType              }   = ""            ;                
    $record->{ DurationHours        }   = 0             ;                
    $record->{ EndDays              }   = 0             ;                
    $record->{ EndTime              }   = 0             ;                
    $record->{ ClosedAuction        }   = 0             ;                
    $record->{ BankDeposit          }   = 0             ;                
    $record->{ CreditCard           }   = 0             ;                
    $record->{ CashOnPickup         }   = 0             ;                
    $record->{ EFTPOS               }   = 0             ;                
    $record->{ Quickpay             }   = 0             ;                
    $record->{ AgreePayMethod       }   = 0             ;                
    $record->{ SafeTrader           }   = 0             ;                
    $record->{ PaymentInfo          }   = ""            ;               
    $record->{ FreeShippingNZ       }   = 0             ;                
    $record->{ ShippingInfo         }   = ""            ;               
    $record->{ PickupOption         }   = 0             ;                
    $record->{ ShippingOption       }   = 0             ;                
    $record->{ Featured             }   = 0             ;                
    $record->{ Gallery              }   = 0             ;                
    $record->{ BoldTitle            }   = 0             ;                
    $record->{ FeatureCombo         }   = 0             ;                
    $record->{ HomePage             }   = 0             ;                
    $record->{ CopyCount            }   = 1             ;                
    $record->{ Message              }   = ""            ;               
    $record->{ PictureKey1          }   = 0             ;                
    $record->{ PictureKey2          }   = 0             ;                
    $record->{ PictureKey3          }   = 0             ;                
    $record->{ AuctionSite          }   = ""            ;               
    $record->{ UserDefined01        }   = ""            ;               
    $record->{ UserDefined02        }   = ""            ;               
    $record->{ UserDefined03        }   = ""            ;               
    $record->{ UserDefined04        }   = ""            ;               
    $record->{ UserDefined05        }   = ""            ;               
    $record->{ UserDefined06        }   = ""            ;               
    $record->{ UserDefined07        }   = ""            ;               
    $record->{ UserDefined08        }   = ""            ;               
    $record->{ UserDefined09        }   = ""            ;               
    $record->{ UserDefined10        }   = ""            ;               
    $record->{ UserStatus           }   = ""            ;               
    $record->{ UserNotes            }   = ""            ;               
    $record->{ OfferPrice           }   = 0             ;               
    $record->{ OfferProcessed       }   = 0             ;               
    $record->{ SaleType             }   = ""            ;               

    # Read through the input values and alter the corresponding fields in the "Record" hash

    while ( ( my $key, my $value ) = each( %{ $input } ) ) {
            $record->{ $key } = $value;
    }

    # Create a fake key, save the old product code and set the product code to the generated key
 
    my $keygen  = "##-".rand;
    my $savprod = $record->{ ProductCode };
    $record->{ ProductCode }   = $keygen;

    $sql_insert_auction_record->execute(                                     
        $record->{ AuctionKey           }, 
       "$record->{ Title                }", 
       "$record->{ Subtitle             }", 
       "$record->{ Description          }",
       "$record->{ ProductType          }",
       "$record->{ ProductCode          }",
       "$record->{ ProductCode2         }",
       "$record->{ SupplierRef          }",
        $record->{ LoadSequence         }, 
        $record->{ Held                 }, 
       "$record->{ AuctionCycle         }",  
       "$record->{ AuctionStatus        }",  
        $record->{ RelistStatus         },  
        $record->{ AuctionSold          },  
        $record->{ StockOnHand          },  
        $record->{ RelistCount          },  
        $record->{ NotifyWatchers       },  
        $record->{ UseTemplate          },  
        $record->{ TemplateKey          },  
       "$record->{ AuctionRef           }",
       "$record->{ SellerRef            }",
       "$record->{ DateLoaded           }",
       "$record->{ CloseDate            }",
       "$record->{ CloseTime            }",
       "$record->{ Category             }",     
        $record->{ MovieRating          },    
        $record->{ MovieConfirm         },    
        $record->{ AttributeCategory    },    
       "$record->{ AttributeName        }",    
       "$record->{ AttributeValue       }",    
       "$record->{ TMATT038             }",    
       "$record->{ TMATT104             }",    
       "$record->{ TMATT104_2           }",    
       "$record->{ TMATT106             }",    
       "$record->{ TMATT106_2           }",    
       "$record->{ TMATT108             }",    
       "$record->{ TMATT108_2           }",    
       "$record->{ TMATT111             }",    
       "$record->{ TMATT112             }",    
       "$record->{ TMATT115             }",    
       "$record->{ TMATT117             }",    
       "$record->{ TMATT118             }",    
       "$record->{ TMATT163             }",    
       "$record->{ TMATT164             }",    
        $record->{ IsNew                },    
        $record->{ TMBuyerEmail         },    
        $record->{ StartPrice           },    
        $record->{ ReservePrice         },      
        $record->{ BuyNowPrice          },    
       "$record->{ EndType              }",    
        $record->{ DurationHours        },    
        $record->{ EndDays              },    
        $record->{ EndTime              },    
        $record->{ ClosedAuction        },    
        $record->{ BankDeposit          },    
        $record->{ CreditCard           },    
        $record->{ CashOnPickup         },    
        $record->{ EFTPOS               },    
        $record->{ Quickpay             },    
        $record->{ AgreePayMethod       },    
        $record->{ SafeTrader           },    
       "$record->{ PaymentInfo          }",    
        $record->{ FreeShippingNZ       },    
       "$record->{ ShippingInfo         }",    
        $record->{ PickupOption         },    
        $record->{ ShippingOption       },    
        $record->{ Featured             },    
        $record->{ Gallery              },    
        $record->{ BoldTitle            },    
        $record->{ FeatureCombo         },    
        $record->{ HomePage             },    
        $record->{ CopyCount            },    
       "$record->{ Message              }",    
        $record->{ PictureKey1          },    
        $record->{ PictureKey2          },    
        $record->{ PictureKey3          },    
       "$record->{ AuctionSite          }",
       "$record->{ UserDefined01        }",
       "$record->{ UserDefined02        }",
       "$record->{ UserDefined03        }",
       "$record->{ UserDefined04        }",
       "$record->{ UserDefined05        }",
       "$record->{ UserDefined06        }",
       "$record->{ UserDefined07        }",
       "$record->{ UserDefined08        }",
       "$record->{ UserDefined09        }",
       "$record->{ UserDefined10        }",
       "$record->{ UserStatus           }",
       "$record->{ UserNotes            }",
        $record->{ OfferPrice           },
        $record->{ OfferProcessed       },
       "$record->{ SaleType             }",
       ) || die "insert-auction - Error executing statement: $DBI::errstr\n";

                    # retrieve the key for the fake product code - should be key of record just added

    # Return the key of the newly added Picture Record

    my $lr = $dbh->last_insert_id("", "", "", "" );
    print $log"Key for last row added: $lr\n";

    return $lr;

    my $rcdkey = get_auction_key_by_productcode( $keygen );

    # Update the record with the correct product code (the saved value)

    update_auction_record(
        AuctionKey          =>  $rcdkey    ,
        ProductCode         =>  $savprod   ,
    );
    
    return $rcdkey;
}
