# formletter_ui.pl --
#
# UI generated by GUI Builder v1.0on 2002-12-01 14:45:53 from:
#	uiC:/Evan/source/Perl/formletter_ui.pl
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the package for this dialog
package formletter;

use Tk;
use Tk::Menu;

# formletter::ui --
#
# ARGS:
#   root     the parent window for this form
#
sub formletter::ui {
    our($root) = @_;


    # Widget Initialization
    our($label_1) = $root->Label(
	-anchor => 'w',
	-text => 'Heading',
    );
    our($text_6) = $root->Text(
	-height => '1',
	-width => '1',
    );
    our($radiobutton_8) = $root->Radiobutton(
	-text => 'radiobutton',
	-variable => 'example_radiobutton',
    );
    our($radiobutton_9) = $root->Radiobutton(
	-text => 'radiobutton',
	-variable => 'example_radiobutton',
    );
    our($radiobutton_10) = $root->Radiobutton(
	-text => 'radiobutton',
	-variable => 'example_radiobutton',
    );
    our($radiobutton_11) = $root->Radiobutton(
	-text => 'radiobutton',
	-variable => 'example_radiobutton',
    );
    our($checkbutton_2) = $root->Checkbutton(
	-text => 'Paragraph',
	-variable => 'Paragraph 1',
    );
    our($text_1) = $root->Text(
	-height => '1',
	-width => '1',
    );
    our($checkbutton_3) = $root->Checkbutton(
	-text => 'checkbutton',
	-variable => 'example_checkbutton',
    );
    our($text_2) = $root->Text(
	-height => '1',
	-width => '1',
    );
    our($checkbutton_4) = $root->Checkbutton(
	-text => 'checkbutton',
	-variable => 'example_checkbutton',
    );
    our($text_4) = $root->Text(
	-height => '1',
	-width => '1',
    );
    our($checkbutton_5) = $root->Checkbutton(
	-text => 'checkbutton',
	-variable => 'example_checkbutton',
    );
    our($text_5) = $root->Text(
	-height => '1',
	-width => '1',
    );
    our($checkbutton_6) = $root->Checkbutton(
	-text => 'checkbutton',
	-variable => 'example_checkbutton',
    );
    our($text_7) = $root->Text(
	-height => '1',
	-width => '1',
    );
    our($button_1) = $root->Button(
	-text => 'button',
    );
    our($button_2) = $root->Button(
	-text => 'button',
    );

    # widget commands

    $text_6->configure(
	-xscrollcommand => \&text_6_xscrollcommand
    );
    $text_6->configure(
	-yscrollcommand => \&text_6_yscrollcommand
    );
    $radiobutton_8->configure(
	-command => \&radiobutton_8_command
    );
    $radiobutton_9->configure(
	-command => \&radiobutton_9_command
    );
    $radiobutton_10->configure(
	-command => \&radiobutton_10_command
    );
    $radiobutton_11->configure(
	-command => \&radiobutton_11_command
    );
    $checkbutton_2->configure(
	-command => \&checkbutton_2_command
    );
    $text_1->configure(
	-xscrollcommand => \&text_1_xscrollcommand
    );
    $text_1->configure(
	-yscrollcommand => \&text_1_yscrollcommand
    );
    $checkbutton_3->configure(
	-command => \&checkbutton_3_command
    );
    $text_2->configure(
	-xscrollcommand => \&text_2_xscrollcommand
    );
    $text_2->configure(
	-yscrollcommand => \&text_2_yscrollcommand
    );
    $checkbutton_4->configure(
	-command => \&checkbutton_4_command
    );
    $text_4->configure(
	-xscrollcommand => \&text_4_xscrollcommand
    );
    $text_4->configure(
	-yscrollcommand => \&text_4_yscrollcommand
    );
    $checkbutton_5->configure(
	-command => \&checkbutton_5_command
    );
    $text_5->configure(
	-xscrollcommand => \&text_5_xscrollcommand
    );
    $text_5->configure(
	-yscrollcommand => \&text_5_yscrollcommand
    );
    $checkbutton_6->configure(
	-command => \&checkbutton_6_command
    );
    $text_7->configure(
	-xscrollcommand => \&text_7_xscrollcommand
    );
    $text_7->configure(
	-yscrollcommand => \&text_7_yscrollcommand
    );
    $button_1->configure(
	-command => \&button_1_command
    );
    $button_2->configure(
	-command => \&button_2_command
    );


    # Geometry Management
    $label_1->grid(
	-in     => $root,
	-column => '1',
	-row    => '1'
    );
    $text_6->grid(
	-in     => $root,
	-column => '2',
	-row    => '1',
	-columnspan => '4',
	-sticky => 'nesw'
    );
    $radiobutton_8->grid(
	-in     => $root,
	-column => '6',
	-row    => '1'
    );
    $radiobutton_9->grid(
	-in     => $root,
	-column => '7',
	-row    => '1'
    );
    $radiobutton_10->grid(
	-in     => $root,
	-column => '8',
	-row    => '1'
    );
    $radiobutton_11->grid(
	-in     => $root,
	-column => '9',
	-row    => '1'
    );
    $checkbutton_2->grid(
	-in     => $root,
	-column => '1',
	-row    => '2'
    );
    $text_1->grid(
	-in     => $root,
	-column => '2',
	-row    => '2',
	-columnspan => '4',
	-sticky => 'nesw'
    );
    $checkbutton_3->grid(
	-in     => $root,
	-column => '1',
	-row    => '3'
    );
    $text_2->grid(
	-in     => $root,
	-column => '2',
	-row    => '3',
	-columnspan => '4',
	-sticky => 'nesw'
    );
    $checkbutton_4->grid(
	-in     => $root,
	-column => '1',
	-row    => '4'
    );
    $text_4->grid(
	-in     => $root,
	-column => '2',
	-row    => '4',
	-columnspan => '4',
	-sticky => 'nesw'
    );
    $checkbutton_5->grid(
	-in     => $root,
	-column => '1',
	-row    => '5'
    );
    $text_5->grid(
	-in     => $root,
	-column => '2',
	-row    => '5',
	-columnspan => '4',
	-sticky => 'nesw'
    );
    $checkbutton_6->grid(
	-in     => $root,
	-column => '1',
	-row    => '6'
    );
    $text_7->grid(
	-in     => $root,
	-column => '2',
	-row    => '6',
	-columnspan => '4',
	-sticky => 'nesw'
    );
    $button_1->grid(
	-in     => $root,
	-column => '3',
	-row    => '7'
    );
    $button_2->grid(
	-in     => $root,
	-column => '4',
	-row    => '7'
    );


    # Resize Behavior
    $root->gridRowconfigure(1, -weight => 0, -minsize => 26, -pad => 0);
    $root->gridRowconfigure(2, -weight => 0, -minsize => 15, -pad => 0);
    $root->gridRowconfigure(3, -weight => 0, -minsize => 20, -pad => 0);
    $root->gridRowconfigure(4, -weight => 0, -minsize => 13, -pad => 0);
    $root->gridRowconfigure(5, -weight => 0, -minsize => 14, -pad => 0);
    $root->gridRowconfigure(6, -weight => 0, -minsize => 18, -pad => 0);
    $root->gridRowconfigure(7, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(1, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(2, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(3, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(4, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(5, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(6, -weight => 0, -minsize => 63, -pad => 0);
    $root->gridColumnconfigure(7, -weight => 0, -minsize => 69, -pad => 0);
    $root->gridColumnconfigure(8, -weight => 0, -minsize => 56, -pad => 0);
    $root->gridColumnconfigure(9, -weight => 0, -minsize => 84, -pad => 0);
}

1;
